name: Build and Deploy
on:
  push:
    branches-ignore:
      - 'main'
      - 'master'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}

      #- name: Deploy
      #  uses: JamesIves/github-pages-deploy-action@4.1.4
      #  with:
      #    branch: gh-pages # The branch the action should deploy to.
      #    folder: docs/env.BRANCH # The folder the action should deploy.

      - name: Deploy
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: vvv@arenadata.io
          build_dir: docs/env.BRANCH
          branch: gh-pages
          jekyll: yes
          # commit_message: custom message # optional
    
